common:
  orchestrator_common:
    attributes:
      deployment_mode: multinode_compute 
      deployment_engine: simplepuppet
    task_uuid: deployment_task

  openstack_common:
   internal_virtual_ip: 10.20.0.254
   public_virtual_ip: 192.168.0.254
   create_networks: true
   fixed_range: 172.16.0.0/16
   floating_range: 192.168.0.0/24
   # swift_loopback: loopback
   nv_physical_volumes:
    - /dev/sdb
   external_ip_info:
     public_net_router: 192.168.0.1
     ext_bridge: 0.0.0.0
     pool_start: 192.168.0.110
     pool_end: 192.168.0.126
   segment_range: 900:999
   network_manager: nova.network.manager.FlatDHCPManager
   auto_assign_floating_ip: true
   quantum_netnode_on_cnt: true
   use_syslog: false
   syslog_server: 127.0.0.1
   mirror_type: default
   quantum: true
   internal_interface: eth0
   public_interface: eth1
   private_interface: eth2
   public_netmask: 255.255.255.0
   internal_netmask: 255.255.255.0
   default_gateway: 192.168.0.1
   nagios_master: fuel-controller-01-simple.testdomain.com
   cinder: true
   cinder_on_computes: true
   swift: false
   repo_proxy: http://10.20.0.100:3128
   deployment_id: '53'
   dns_nameservers:
   - 10.20.0.100
   - 8.8.8.8
   nodes:
   - name: fuel-pm
     role: cobbler
     internal_address: 10.20.0.100
     public_address: 192.168.0.100
   - name: fuel-controller-01-simple
     role: primary-controller
     internal_address: 10.20.0.101
     public_address: 192.168.0.101
   - name: fuel-controller-01-simple
     role: quantum
     internal_address: 10.20.0.101
     public_address: 192.168.0.101
   
   - name: fuel-controller-01-simple
     role: storage
     internal_address: 10.20.0.101
     public_address: 192.168.0.101

   - name: fuel-compute-01-simple
     role: compute
     internal_address: 10.20.0.110
     public_address: 192.168.0.110



  cobbler_common:
    # for Centos
    profile: "centos63_x86_64"
    # for Ubuntu
    # profile: "ubuntu_1204_x86_64"
    netboot-enabled: "1"
    # for Ubuntu
    # ksmeta: "puppet_version=2.7.19-1puppetlabs2 \
    # for Centos
    name-servers: "10.20.0.100"
    name-servers-search: "testdomain.com"
    gateway: 10.20.0.100
    ksmeta: "puppet_version=2.7.19-1.el6 \
      puppet_auto_setup=1 \
      puppet_master=fuel-pm.testdomain.com \
      puppet_enable=0 \
      ntp_enable=1 \
      mco_auto_setup=1 \
      mco_pskey=un0aez2ei9eiGaequaey4loocohjuch4Ievu3shaeweeg5Uthi \
      mco_stomphost=10.20.0.100 \
      mco_stompport=61613 \
      mco_stompuser=mcollective \
      mco_stomppassword=AeN5mi5thahz2Aiveexo \
      mco_enable=1"


fuel-controller-01-simple:
  hostname: "fuel-controller-01-simple"
  role: primary-controller
  interfaces:
    eth0:
      mac: "52:54:00:9c:f5:58"
      static: "1"
      ip-address: "10.20.0.101"
      netmask: "255.255.255.0"
      dns-name: "fuel-controller-01-simple.testdomain.com"
      management: "1"
    eth1:
      mac: "52:54:00:e5:25:3f"
      static: "0"
    eth2:
      mac: "52:54:00:dd:29:7c"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-compute-01-simple:
  hostname: "fuel-compute-01-simple"
  role: compute
  interfaces:
    eth0:
      mac: "52:54:00:17:3c:4d"
      static: "1"
      ip-address: "10.20.0.110"
      netmask: "255.255.255.0"
      dns-name: "fuel-compute-01-simple.testdomain.com"
      management: "1"
    eth1:
      mac: "52:54:00:12:ba:7a"
      static: "0"
    eth2:
      mac: "52:54:00:c1:0d:9f"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"
